name: NetScan
version: "1.0.6"
slug: netscan
description: LAN device inventory & scanner (ICMP/ARP/TCP) with scan history
url: "https://github.com/Koen-Schockaert/network-navigator-66"
image: "ghcr.io/koen-schockaert/netscan"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
host_network: true
privileged:
  - NET_RAW
  - NET_ADMIN
webui: "http://[HOST]:[PORT:8099]/"
options:
  port: 8099
  default_subnet: ""
  interval_minutes: 0
schema:
  port: "port"
  default_subnet: "str?"
  interval_minutes: "int(0,1440)?"
