name: NetScan
version: "1.0.6"
slug: netscan
description: LAN device inventory & scanner (ICMP/ARP/TCP) with scan history
url: "https://github.com/Koen-Schockaert/network-navigator-66"
image: "ghcr.io/koen-schockaert/netscan"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
host_network: true
privileged:
  - NET_RAW
  - NET_ADMIN
ingress: true
ingress_port: 8099
panel_icon: mdi:lan
panel_title: NetScan
panel_admin: true
options:
  default_subnet: ""
  interval_minutes: 0
schema:
  default_subnet: "str?"
  interval_minutes: "int(0,1440)?"
